### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by web3cryptowallet** [thomscoder/glowhub#1]
Please see the attached screenshot:
![Screenshot 2024-12-10 at 18 31 41](https://github.com/user-attachments/assets/d0947280-57f2-4de1-9528-572eea30d37d)

**Comment by thomscoder** [comment]
![0e0129c2-fb5f-40f2-96d3-9bf7e0ddbb91](https://github.com/user-attachments/assets/53d0553f-b15c-42d0-91bb-a821ecc09c72)

Should be fixed
